---
title: "Homework for Class 6 - Write a Function"
author: "Jessica Le (PID: A17321021)"
format: html
---

## Can you improve this analysis code?

```{r}
#Call installed bio3d database
library(bio3d)

#Takes the input in the form of a pdb code and creates pdb file that is read using function `read.pdb` 
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug

#trimming the PDB structures to a smaller subset of atoms using function `trim.pdb`
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s1, chain="A", elety="CA")

#Selecting beta factor from for atom
s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b

#Plot beta factor for atom
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```

This is the generated function. The function trims the by selecting chain A, and the output is plotting the beta factor
```{r}
library(bio3d)
plot_pdb <- function(pdb_code) {
  s <- read.pdb(pdb_code)
  s.chainA <- trim.pdb(s, chain="A", elety="CA")
  s.b <- s.chainA$atom$b
  plotb3(s.b, sse=s.chainA, typ="l", ylab="Bfactor") 
}
```

This is an analysis of the generated function. 
```{r}
#Call installed bio3d database
library(bio3d)

#Takes the input in the form of a pdb code and creates pdb file that is read using function `read.pdb` 
plot_pdb <- function(pdb_code) {
  
#trimming the PDB structures to a smaller subset of atoms using function `trim.pdb` and the input is the pdb code
  s <- read.pdb(pdb_code)
  
#Selecting beta factor from for atom and the input is s
  s.chainA <- trim.pdb(s, chain="A", elety="CA")
  
#
  s.b <- s.chainA$atom$b
  plotb3(s.b, sse=s.chainA, typ="l", ylab="Bfactor") 
}
```

Testing out the generated function. 
```{r}
sapply(c("4AKE", "1AKE", "1E4Y"), FUN=plot_pdb)
```
